### ISSUE TITLE
Advanced Installation on Digital Ocean / Runcloud

### ISSUE THREAD

**Issue by mark-chief** [bullhorn/career-portal#375]
Hello I am struggling to install the advanced version of the career portal.

**Server Info:**
Host Digital Ocean, Ubuntu
Angular CLI v7.3.10
npm v 6.14.11
node.js v 12.21.0

I get as far these steps..

```
git clone https://github.com/bullhorn/career-portal.git
```

Change to the Career Portal directory:

```
cd career-portal
```

Install build tools and dev dependencies:

```
npm install
```
...Takes a while.. and then displays a build error:
```
/home/runcloud/.node-gyp/12.21.0/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
make: *** [binding.target.mk:131: Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/home/runcloud/webapps/career-portal/career-portal/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/runcloud/webapps/career-portal/career-portal/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-51-generic
gyp ERR! command "/usr/bin/node" "/home/runcloud/webapps/career-portal/career-portal/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/runcloud/webapps/career-portal/career-portal/node_modules/node-sass
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1363 packages from 1307 contributors and audited 1432 packages in 305.084s

24 packages are looking for funding
  run `npm fund` for details

found 33 vulnerabilities (10 low, 10 moderate, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

Thanks for your help!!

(This is not a wordpress site so do not need Matador)

**Comment by mark-chief** [comment]
A side question, related to the next step in your docs:

```
npm run serve           # Launch a local version of the career portal (frontend only).
npm start               # Launch a local server with server side rendering portal.
npm run build:static    # Build an optimized version of Career Portal in `/dist`
npm run build          # Build a package for use with server side rendering
```
Which one is the correct option to choose? I basically just need the XML/RSS feed publicly accessble.

**Comment by charlesabarnes** [comment]
Hello, the node-sass version currently in use by the career portal does not support Node 12.  I suggest using [nvm](https://github.com/nvm-sh/nvm)/[nvm windows](https://github.com/coreybutler/nvm-windows) to temporarily downgrade to 10 to build the portal

Since you are doing the advanced installation you would want just `npm run build`.

However, to run the application you will probably want to utilize a tool such as [PM2](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04)

Please let me know if you have any more questions

**Comment by mark-chief** [comment]
Hello Charles, thanks for your help. I adjusted the node version and it seems to install better.

I am slightly confused by the steps that set a port number and PM2. I have PM2 installed.

Which folder is the public folder I should point my public domain to? I think I am nearly there I just need to get it running. I have not used nodejs, npm, angular, pm2 before!

Thanks so much!

<img width="247" alt="Screenshot 2021-03-19 at 09 51 02" src="https://user-images.githubusercontent.com/18699249/111762305-cbc4a200-8898-11eb-8707-c1287d155465.png">

**Comment by charlesabarnes** [comment]
Hello,

The Advanced Installation/Node apps are not static websites that you can point a domain to and it works.  The /dist directory would need to be transferred to your host, then you will need to run `node server.js` or utilize a tool such as pm2 to run it.

**Comment by mark-chief** [comment]
The directory screenshot I attached previously is on my host server already, would I `cd` to the /dist folder and run `node server.js` ? Sorry for my lack on knowledge in this area!

**Comment by charlesabarnes** [comment]
Yeah, that is correct

**Comment by mark-chief** [comment]
OK so I have done that and pointed my domain to the `/dist/browser` directory. 
But trying to access the /sitemap or /feed and getting a 404 [Link here](http://career-portal.8y5vsjqpax-lxd6r8qjk39g.p.runcloud.link/feed)

**Comment by charlesabarnes** [comment]
So your domain needs to map to the IP address and port that the node app is running at.   I found some digital ocean documentation that goes over this and it can be found below.

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-20-04#step-4-%E2%80%94-setting-up-nginx-as-a-reverse-proxy-server

**Comment by mark-chief** [comment]
That was very helpful, thanks! It is up and running now. 

I have a question that isn't directly related to this thread, but is there a way for me to pull more fields from bullhorn vacancies in to the RSS feed? E.g category Thanks again

**Comment by charlesabarnes** [comment]
Yeah. This would require modifications to the https://github.com/bullhorn/career-portal/blob/master/generateXml.ts file.  You can add as many properties as you need

**Comment by charlesabarnes** [comment]
Closing this for now. Please let me know if you have any questions

**Comment by mark-chief** [comment]
Hello, I have been making changes to that file but they are not reflected on the front end...

**Comment by charlesabarnes** [comment]
Hello, when a change is made to the file, you have to rebuild before it is reflected

**Comment by mark-chief** [comment]
Hmm, I am not getting anywhere with this,

Running `ng build` with no joy. 

I also tried restarting PM2 after `pm2 restart server`

I am editing `/career-portal/generateXml.ts`

Thanks

**Comment by charlesabarnes** [comment]
`npm run build` is the required build command

**Comment by mark-chief** [comment]
Hello Charles,

`npm run build` completes successfully but the changes I make to the generateXML.ts are not reflected.

is career-portal/generateXml.ts the correct file to be editing or is there another instance of this file in the /career-portal/src  or anywhere else?

```
$ npm run build

> career-portal@3.2.0 build /home/runcloud/webapps/career-portal/career-portal
> npm run build:ssr


> career-portal@3.2.0 build:ssr /home/runcloud/webapps/career-portal/career-portal
> npm run build:client-and-server-bundles && npm run compile:server


> career-portal@3.2.0 build:client-and-server-bundles /home/runcloud/webapps/career-portal/career-portal
> ng build --prod --configuration=dynamic && ng run career-portal:server:dynamic

                                                                                         
Date: 2021-03-22T09:52:26.189Z
Hash: 0073659716a35632e3af
Time: 142444ms
chunk {0} runtime.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.js (main) 2.25 MB [initial] [rendered]
chunk {2} polyfills.js (polyfills) 41 kB [initial] [rendered]
chunk {3} styles.css (styles) 856 kB [initial] [rendered]
Date: 2021-03-22T09:53:21.409Z
Hash: 147ed67f5b30135a2a1d
Time: 44207ms
chunk {main} main.js, main.js.map (main) 1.94 MB [entry] [rendered]

> career-portal@3.2.0 compile:server /home/runcloud/webapps/career-portal/career-portal
> webpack --config webpack.server.config.js --progress --colors

Hash: bd82918bba349386315b                                                                
Version: webpack 4.23.1
Time: 31134ms
Built at: 03/22/2021 9:53:56 AM
    Asset      Size  Chunks             Chunk Names
server.js  11.5 MiB       0  [emitted]  server
Entrypoint server = server.js
  [0] ./server.ts 3.57 KiB {0} [built]
  [2] external "events" 42 bytes {0} [built]
  [3] external "fs" 42 bytes {0} [built]
  [4] external "timers" 42 bytes {0} [optional] [built]
  [5] external "crypto" 42 bytes {0} [built]
[208] ./src lazy namespace object 160 bytes {0} [built]
[220] external "url" 42 bytes {0} [built]
[276] external "http" 42 bytes {0} [built]
[277] external "https" 42 bytes {0} [built]
[278] external "os" 42 bytes {0} [built]
[282] external "child_process" 42 bytes {0} [built]
[290] external "path" 42 bytes {0} [built]
[385] (webpack)/buildin/module.js 497 bytes {0} [built]
[398] ./generateXml.ts 4.24 KiB {0} [built]
[400] ./dist/server/main.js 1.94 MiB {0} [built]
    + 587 hidden modules
```
Thank you for your patience and help so far.

**Comment by charlesabarnes** [comment]
That is 100% the correct file. It's the only location that takes care of the XML generation. Make sure you are restarting the pm2 run after each build. Make sure you are also editing the method for the specific endpoint you are hitting

**Comment by mark-chief** [comment]
Thanks so much. it was the `pm2 restart server! Thanks for guiding me through this, I really appreciate it.

**Comment by pbearne** [comment]
Hi Mark

I have following along with your efforts
I am confused as to what is the end goal here?

What do you need the RSS/XML for?
What extra fields are you adding?

Paul

**Comment by mark-chief** [comment]
BullHorn do not offer (or not that I am aware of) a basic RSS feed of job listings. We needed to consume an RSS feed in our app, and also a third party app requires an RSS feed of our jobs too.

**Comment by pbearne** [comment]
Hi Mark,

It looks like your client is the Masentó Group if that is the case they have Matador jobs installed https://www.masentogroup.com/job/technical-support-lead/ on their WP site so you could pull the jobs from there.
We disable the default RSS for jobs listing as it not much use as its missing job-related data 

So we have an add-on https://matadorjobs.com/products/jobs-xml-feeds/ which creates custom XML feeds for the job-related data 

Here's an example https://demo.matadorjobs.com/gigs/xml/

You could add your own version or just use a standard version if it has what you need.

Going this route might save you a lot of effort and save you having to maintain a server install.

Paul

**Comment by mark-chief** [comment]
This is a separate project not related to their WP website. 
Would you mind removing their company name from this thread too? Thanks
The WP plugin does lots and looks great, but we're not using WP.

**Comment by pbearne** [comment]
Company removed 

I was assuming that you just needed a feed of their jobs for your app all the info you need (and more) is on their website
Even better the jobs data is also available in the WP Rest API with a full GraphQL schema with this https://github.com/wp-graphql/wp-graphql which would save you having to process the RSS feed.

Paul

**Comment by mark-chief** [comment]
Thanks Paul, Appreciate the help, looks great!

**Comment by mark-chief** [comment]
Hello Charles, we have added `customtext20` field to Vacancies, do we need to contact BullHorn to that field exposed so we can use in the RSS feed? As at the moment it is not pulling through data. Thanks

**Comment by charlesabarnes** [comment]
Hello, that's correct
